package com.tkj.wechat.dao;

import com.tkj.wechat.domain.ClassType;
import com.tkj.wechat.domain.ClassTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    long countByExample(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    int deleteByExample(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    int insert(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    int insertSelective(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    ClassType selectOneByExample(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    ClassType selectOneByExampleSelective(@Param("example") ClassTypeExample example, @Param("selective") ClassType.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    ClassType selectOneByExampleWithBLOBs(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    List<ClassType> selectByExampleSelective(@Param("example") ClassTypeExample example, @Param("selective") ClassType.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    List<ClassType> selectByExampleWithBLOBs(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    List<ClassType> selectByExample(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    ClassType selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ClassType.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    ClassType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    ClassType selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ClassType record, @Param("example") ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ClassType record, @Param("example") ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ClassType record, @Param("example") ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}