package com.tkj.wechat.dao;

import com.tkj.wechat.domain.ClassPermission;
import com.tkj.wechat.domain.ClassPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    long countByExample(ClassPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    int deleteByExample(ClassPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    int insert(ClassPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    int insertSelective(ClassPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    ClassPermission selectOneByExample(ClassPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    ClassPermission selectOneByExampleSelective(@Param("example") ClassPermissionExample example, @Param("selective") ClassPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    List<ClassPermission> selectByExampleSelective(@Param("example") ClassPermissionExample example, @Param("selective") ClassPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    List<ClassPermission> selectByExample(ClassPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    ClassPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ClassPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    ClassPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ClassPermission record, @Param("example") ClassPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ClassPermission record, @Param("example") ClassPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ClassPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ClassPermission record);
}