package com.tkj.wechat.dao;

import com.tkj.wechat.domain.TeacherOrderApplication;
import com.tkj.wechat.domain.TeacherOrderApplicationExample;
import com.tkj.wechat.domain.TeacherOrderApplicationWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherOrderApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    long countByExample(TeacherOrderApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    int deleteByExample(TeacherOrderApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    int insert(TeacherOrderApplicationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    int insertSelective(TeacherOrderApplicationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    TeacherOrderApplication selectOneByExample(TeacherOrderApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    TeacherOrderApplicationWithBLOBs selectOneByExampleSelective(@Param("example") TeacherOrderApplicationExample example, @Param("selective") TeacherOrderApplicationWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    TeacherOrderApplicationWithBLOBs selectOneByExampleWithBLOBs(TeacherOrderApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    List<TeacherOrderApplicationWithBLOBs> selectByExampleSelective(@Param("example") TeacherOrderApplicationExample example, @Param("selective") TeacherOrderApplicationWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    List<TeacherOrderApplicationWithBLOBs> selectByExampleWithBLOBs(TeacherOrderApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    List<TeacherOrderApplication> selectByExample(TeacherOrderApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    TeacherOrderApplicationWithBLOBs selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TeacherOrderApplicationWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    TeacherOrderApplicationWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TeacherOrderApplicationWithBLOBs record, @Param("example") TeacherOrderApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TeacherOrderApplicationWithBLOBs record, @Param("example") TeacherOrderApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TeacherOrderApplication record, @Param("example") TeacherOrderApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeacherOrderApplicationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TeacherOrderApplicationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_order_application
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacherOrderApplication record);
}