package com.tkj.wechat.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class Authentication {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentication.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentication.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentication.authentication_type
     *
     * @mbg.generated
     */
    private Integer authenticationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentication.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentication.identity_number
     *
     * @mbg.generated
     */
    private String identityNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentication.identity_name
     *
     * @mbg.generated
     */
    private String identityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentication.identity_card_front_id
     *
     * @mbg.generated
     */
    private Integer identityCardFrontId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentication.identity_card_reverse_id
     *
     * @mbg.generated
     */
    private Integer identityCardReverseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentication.education_code
     *
     * @mbg.generated
     */
    private String educationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentication.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentication.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentication.record
     *
     * @mbg.generated
     */
    private String record;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentication.id
     *
     * @return the value of authentication.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentication.id
     *
     * @param id the value for authentication.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentication.user_id
     *
     * @return the value of authentication.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentication.user_id
     *
     * @param userId the value for authentication.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentication.authentication_type
     *
     * @return the value of authentication.authentication_type
     *
     * @mbg.generated
     */
    public Integer getAuthenticationType() {
        return authenticationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentication.authentication_type
     *
     * @param authenticationType the value for authentication.authentication_type
     *
     * @mbg.generated
     */
    public void setAuthenticationType(Integer authenticationType) {
        this.authenticationType = authenticationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentication.state
     *
     * @return the value of authentication.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentication.state
     *
     * @param state the value for authentication.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentication.identity_number
     *
     * @return the value of authentication.identity_number
     *
     * @mbg.generated
     */
    public String getIdentityNumber() {
        return identityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentication.identity_number
     *
     * @param identityNumber the value for authentication.identity_number
     *
     * @mbg.generated
     */
    public void setIdentityNumber(String identityNumber) {
        this.identityNumber = identityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentication.identity_name
     *
     * @return the value of authentication.identity_name
     *
     * @mbg.generated
     */
    public String getIdentityName() {
        return identityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentication.identity_name
     *
     * @param identityName the value for authentication.identity_name
     *
     * @mbg.generated
     */
    public void setIdentityName(String identityName) {
        this.identityName = identityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentication.identity_card_front_id
     *
     * @return the value of authentication.identity_card_front_id
     *
     * @mbg.generated
     */
    public Integer getIdentityCardFrontId() {
        return identityCardFrontId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentication.identity_card_front_id
     *
     * @param identityCardFrontId the value for authentication.identity_card_front_id
     *
     * @mbg.generated
     */
    public void setIdentityCardFrontId(Integer identityCardFrontId) {
        this.identityCardFrontId = identityCardFrontId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentication.identity_card_reverse_id
     *
     * @return the value of authentication.identity_card_reverse_id
     *
     * @mbg.generated
     */
    public Integer getIdentityCardReverseId() {
        return identityCardReverseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentication.identity_card_reverse_id
     *
     * @param identityCardReverseId the value for authentication.identity_card_reverse_id
     *
     * @mbg.generated
     */
    public void setIdentityCardReverseId(Integer identityCardReverseId) {
        this.identityCardReverseId = identityCardReverseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentication.education_code
     *
     * @return the value of authentication.education_code
     *
     * @mbg.generated
     */
    public String getEducationCode() {
        return educationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentication.education_code
     *
     * @param educationCode the value for authentication.education_code
     *
     * @mbg.generated
     */
    public void setEducationCode(String educationCode) {
        this.educationCode = educationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentication.add_time
     *
     * @return the value of authentication.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentication.add_time
     *
     * @param addTime the value for authentication.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentication.update_time
     *
     * @return the value of authentication.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentication.update_time
     *
     * @param updateTime the value for authentication.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentication.record
     *
     * @return the value of authentication.record
     *
     * @mbg.generated
     */
    public String getRecord() {
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentication.record
     *
     * @param record the value for authentication.record
     *
     * @mbg.generated
     */
    public void setRecord(String record) {
        this.record = record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authentication
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", authenticationType=").append(authenticationType);
        sb.append(", state=").append(state);
        sb.append(", identityNumber=").append(identityNumber);
        sb.append(", identityName=").append(identityName);
        sb.append(", identityCardFrontId=").append(identityCardFrontId);
        sb.append(", identityCardReverseId=").append(identityCardReverseId);
        sb.append(", educationCode=").append(educationCode);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", record=").append(record);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authentication
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Authentication other = (Authentication) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getAuthenticationType() == null ? other.getAuthenticationType() == null : this.getAuthenticationType().equals(other.getAuthenticationType()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getIdentityNumber() == null ? other.getIdentityNumber() == null : this.getIdentityNumber().equals(other.getIdentityNumber()))
            && (this.getIdentityName() == null ? other.getIdentityName() == null : this.getIdentityName().equals(other.getIdentityName()))
            && (this.getIdentityCardFrontId() == null ? other.getIdentityCardFrontId() == null : this.getIdentityCardFrontId().equals(other.getIdentityCardFrontId()))
            && (this.getIdentityCardReverseId() == null ? other.getIdentityCardReverseId() == null : this.getIdentityCardReverseId().equals(other.getIdentityCardReverseId()))
            && (this.getEducationCode() == null ? other.getEducationCode() == null : this.getEducationCode().equals(other.getEducationCode()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getRecord() == null ? other.getRecord() == null : this.getRecord().equals(other.getRecord()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authentication
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAuthenticationType() == null) ? 0 : getAuthenticationType().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getIdentityNumber() == null) ? 0 : getIdentityNumber().hashCode());
        result = prime * result + ((getIdentityName() == null) ? 0 : getIdentityName().hashCode());
        result = prime * result + ((getIdentityCardFrontId() == null) ? 0 : getIdentityCardFrontId().hashCode());
        result = prime * result + ((getIdentityCardReverseId() == null) ? 0 : getIdentityCardReverseId().hashCode());
        result = prime * result + ((getEducationCode() == null) ? 0 : getEducationCode().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getRecord() == null) ? 0 : getRecord().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table authentication
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        userId("user_id", "userId", "INTEGER", false),
        authenticationType("authentication_type", "authenticationType", "INTEGER", false),
        state("state", "state", "INTEGER", true),
        identityNumber("identity_number", "identityNumber", "VARCHAR", false),
        identityName("identity_name", "identityName", "VARCHAR", false),
        identityCardFrontId("identity_card_front_id", "identityCardFrontId", "INTEGER", false),
        identityCardReverseId("identity_card_reverse_id", "identityCardReverseId", "INTEGER", false),
        educationCode("education_code", "educationCode", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        record("record", "record", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table authentication
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table authentication
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table authentication
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table authentication
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table authentication
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table authentication
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table authentication
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table authentication
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table authentication
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table authentication
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table authentication
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table authentication
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table authentication
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table authentication
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table authentication
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table authentication
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table authentication
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}