package com.tkj.wechat.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;

public class ClassType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class_type
     *
     * @mbg.generated
     */
    public static final Integer IS_DELETED = IsDelete.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class_type
     *
     * @mbg.generated
     */
    public static final Integer NOT_DELETED = IsDelete.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_type.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_type.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_type.min_capacity
     *
     * @mbg.generated
     */
    private Integer minCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_type.max_capacity
     *
     * @mbg.generated
     */
    private Integer maxCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_type.min_lesson_number
     *
     * @mbg.generated
     */
    private Integer minLessonNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_type.max_lesson_number
     *
     * @mbg.generated
     */
    private Integer maxLessonNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_type.lesson_price
     *
     * @mbg.generated
     */
    private BigDecimal lessonPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_type.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_type.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_type.id
     *
     * @return the value of class_type.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_type.id
     *
     * @param id the value for class_type.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_type.type_name
     *
     * @return the value of class_type.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_type.type_name
     *
     * @param typeName the value for class_type.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_type.min_capacity
     *
     * @return the value of class_type.min_capacity
     *
     * @mbg.generated
     */
    public Integer getMinCapacity() {
        return minCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_type.min_capacity
     *
     * @param minCapacity the value for class_type.min_capacity
     *
     * @mbg.generated
     */
    public void setMinCapacity(Integer minCapacity) {
        this.minCapacity = minCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_type.max_capacity
     *
     * @return the value of class_type.max_capacity
     *
     * @mbg.generated
     */
    public Integer getMaxCapacity() {
        return maxCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_type.max_capacity
     *
     * @param maxCapacity the value for class_type.max_capacity
     *
     * @mbg.generated
     */
    public void setMaxCapacity(Integer maxCapacity) {
        this.maxCapacity = maxCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_type.min_lesson_number
     *
     * @return the value of class_type.min_lesson_number
     *
     * @mbg.generated
     */
    public Integer getMinLessonNumber() {
        return minLessonNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_type.min_lesson_number
     *
     * @param minLessonNumber the value for class_type.min_lesson_number
     *
     * @mbg.generated
     */
    public void setMinLessonNumber(Integer minLessonNumber) {
        this.minLessonNumber = minLessonNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_type.max_lesson_number
     *
     * @return the value of class_type.max_lesson_number
     *
     * @mbg.generated
     */
    public Integer getMaxLessonNumber() {
        return maxLessonNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_type.max_lesson_number
     *
     * @param maxLessonNumber the value for class_type.max_lesson_number
     *
     * @mbg.generated
     */
    public void setMaxLessonNumber(Integer maxLessonNumber) {
        this.maxLessonNumber = maxLessonNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_type.lesson_price
     *
     * @return the value of class_type.lesson_price
     *
     * @mbg.generated
     */
    public BigDecimal getLessonPrice() {
        return lessonPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_type.lesson_price
     *
     * @param lessonPrice the value for class_type.lesson_price
     *
     * @mbg.generated
     */
    public void setLessonPrice(BigDecimal lessonPrice) {
        this.lessonPrice = lessonPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setIsDelete(deleted ? IsDelete.IS_DELETED.value() : IsDelete.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_type.is_delete
     *
     * @return the value of class_type.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_type.is_delete
     *
     * @param isDelete the value for class_type.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_type.detail
     *
     * @return the value of class_type.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_type.detail
     *
     * @param detail the value for class_type.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", typeName=").append(typeName);
        sb.append(", minCapacity=").append(minCapacity);
        sb.append(", maxCapacity=").append(maxCapacity);
        sb.append(", minLessonNumber=").append(minLessonNumber);
        sb.append(", maxLessonNumber=").append(maxLessonNumber);
        sb.append(", lessonPrice=").append(lessonPrice);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", detail=").append(detail);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ClassType other = (ClassType) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTypeName() == null ? other.getTypeName() == null : this.getTypeName().equals(other.getTypeName()))
            && (this.getMinCapacity() == null ? other.getMinCapacity() == null : this.getMinCapacity().equals(other.getMinCapacity()))
            && (this.getMaxCapacity() == null ? other.getMaxCapacity() == null : this.getMaxCapacity().equals(other.getMaxCapacity()))
            && (this.getMinLessonNumber() == null ? other.getMinLessonNumber() == null : this.getMinLessonNumber().equals(other.getMinLessonNumber()))
            && (this.getMaxLessonNumber() == null ? other.getMaxLessonNumber() == null : this.getMaxLessonNumber().equals(other.getMaxLessonNumber()))
            && (this.getLessonPrice() == null ? other.getLessonPrice() == null : this.getLessonPrice().equals(other.getLessonPrice()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getDetail() == null ? other.getDetail() == null : this.getDetail().equals(other.getDetail()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTypeName() == null) ? 0 : getTypeName().hashCode());
        result = prime * result + ((getMinCapacity() == null) ? 0 : getMinCapacity().hashCode());
        result = prime * result + ((getMaxCapacity() == null) ? 0 : getMaxCapacity().hashCode());
        result = prime * result + ((getMinLessonNumber() == null) ? 0 : getMinLessonNumber().hashCode());
        result = prime * result + ((getMaxLessonNumber() == null) ? 0 : getMaxLessonNumber().hashCode());
        result = prime * result + ((getLessonPrice() == null) ? 0 : getLessonPrice().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getDetail() == null) ? 0 : getDetail().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table class_type
     *
     * @mbg.generated
     */
    public enum IsDelete {
        NOT_DELETED(new Integer("0"), "未删除"),
        IS_DELETED(new Integer("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table class_type
         *
         * @mbg.generated
         */
        private final Integer value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table class_type
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        IsDelete(Integer value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public Integer getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public Integer value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public static IsDelete parseValue(Integer value) {
            if (value != null) {
                for (IsDelete item : values()) {
                    if (item.value.equals(value)) {
                        return item;
                    }
                }
            }
            return null;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public static IsDelete parseName(String name) {
            if (name != null) {
                for (IsDelete item : values()) {
                    if (item.name.equals(name)) {
                        return item;
                    }
                }
            }
            return null;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table class_type
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        typeName("type_name", "typeName", "VARCHAR", false),
        minCapacity("min_capacity", "minCapacity", "INTEGER", false),
        maxCapacity("max_capacity", "maxCapacity", "INTEGER", false),
        minLessonNumber("min_lesson_number", "minLessonNumber", "INTEGER", false),
        maxLessonNumber("max_lesson_number", "maxLessonNumber", "INTEGER", false),
        lessonPrice("lesson_price", "lessonPrice", "DECIMAL", false),
        isDelete("is_delete", "isDelete", "INTEGER", false),
        detail("detail", "detail", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table class_type
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table class_type
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table class_type
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table class_type
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table class_type
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table class_type
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table class_type
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}