package com.tkj.wechat.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class ViewClassTypePoster {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_class_type_poster.class_type_id
     *
     * @mbg.generated
     */
    private Integer classTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_class_type_poster.class_type_name
     *
     * @mbg.generated
     */
    private String classTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_class_type_poster.poster_id
     *
     * @mbg.generated
     */
    private Integer posterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_class_type_poster.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_class_type_poster.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_class_type_poster.sequence
     *
     * @mbg.generated
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_class_type_poster.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_class_type_poster.class_type_detail
     *
     * @mbg.generated
     */
    private String classTypeDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_class_type_poster.class_type_id
     *
     * @return the value of view_class_type_poster.class_type_id
     *
     * @mbg.generated
     */
    public Integer getClassTypeId() {
        return classTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_class_type_poster.class_type_id
     *
     * @param classTypeId the value for view_class_type_poster.class_type_id
     *
     * @mbg.generated
     */
    public void setClassTypeId(Integer classTypeId) {
        this.classTypeId = classTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_class_type_poster.class_type_name
     *
     * @return the value of view_class_type_poster.class_type_name
     *
     * @mbg.generated
     */
    public String getClassTypeName() {
        return classTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_class_type_poster.class_type_name
     *
     * @param classTypeName the value for view_class_type_poster.class_type_name
     *
     * @mbg.generated
     */
    public void setClassTypeName(String classTypeName) {
        this.classTypeName = classTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_class_type_poster.poster_id
     *
     * @return the value of view_class_type_poster.poster_id
     *
     * @mbg.generated
     */
    public Integer getPosterId() {
        return posterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_class_type_poster.poster_id
     *
     * @param posterId the value for view_class_type_poster.poster_id
     *
     * @mbg.generated
     */
    public void setPosterId(Integer posterId) {
        this.posterId = posterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_class_type_poster.url
     *
     * @return the value of view_class_type_poster.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_class_type_poster.url
     *
     * @param url the value for view_class_type_poster.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_class_type_poster.type
     *
     * @return the value of view_class_type_poster.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_class_type_poster.type
     *
     * @param type the value for view_class_type_poster.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_class_type_poster.sequence
     *
     * @return the value of view_class_type_poster.sequence
     *
     * @mbg.generated
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_class_type_poster.sequence
     *
     * @param sequence the value for view_class_type_poster.sequence
     *
     * @mbg.generated
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_class_type_poster.is_delete
     *
     * @return the value of view_class_type_poster.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_class_type_poster.is_delete
     *
     * @param isDelete the value for view_class_type_poster.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_class_type_poster.class_type_detail
     *
     * @return the value of view_class_type_poster.class_type_detail
     *
     * @mbg.generated
     */
    public String getClassTypeDetail() {
        return classTypeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_class_type_poster.class_type_detail
     *
     * @param classTypeDetail the value for view_class_type_poster.class_type_detail
     *
     * @mbg.generated
     */
    public void setClassTypeDetail(String classTypeDetail) {
        this.classTypeDetail = classTypeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_class_type_poster
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", classTypeId=").append(classTypeId);
        sb.append(", classTypeName=").append(classTypeName);
        sb.append(", posterId=").append(posterId);
        sb.append(", url=").append(url);
        sb.append(", type=").append(type);
        sb.append(", sequence=").append(sequence);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", classTypeDetail=").append(classTypeDetail);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_class_type_poster
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ViewClassTypePoster other = (ViewClassTypePoster) that;
        return (this.getClassTypeId() == null ? other.getClassTypeId() == null : this.getClassTypeId().equals(other.getClassTypeId()))
            && (this.getClassTypeName() == null ? other.getClassTypeName() == null : this.getClassTypeName().equals(other.getClassTypeName()))
            && (this.getPosterId() == null ? other.getPosterId() == null : this.getPosterId().equals(other.getPosterId()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getSequence() == null ? other.getSequence() == null : this.getSequence().equals(other.getSequence()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getClassTypeDetail() == null ? other.getClassTypeDetail() == null : this.getClassTypeDetail().equals(other.getClassTypeDetail()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_class_type_poster
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getClassTypeId() == null) ? 0 : getClassTypeId().hashCode());
        result = prime * result + ((getClassTypeName() == null) ? 0 : getClassTypeName().hashCode());
        result = prime * result + ((getPosterId() == null) ? 0 : getPosterId().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getSequence() == null) ? 0 : getSequence().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getClassTypeDetail() == null) ? 0 : getClassTypeDetail().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table view_class_type_poster
     *
     * @mbg.generated
     */
    public enum Column {
        classTypeId("class_type_id", "classTypeId", "INTEGER", false),
        classTypeName("class_type_name", "classTypeName", "VARCHAR", false),
        posterId("poster_id", "posterId", "INTEGER", false),
        url("url", "url", "VARCHAR", false),
        type("type", "type", "VARCHAR", true),
        sequence("sequence", "sequence", "INTEGER", true),
        isDelete("is_delete", "isDelete", "INTEGER", false),
        classTypeDetail("class_type_detail", "classTypeDetail", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_class_type_poster
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}